
name: BuildTest

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [kinetic, melodic, noetic, foxy, galactic]
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Setup ROS ${{ matrix.rosdistro }} environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}
      - name: Run build test for ${{ matrix.package }} package
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ matrix.package }}
          target-ros2-distro: ${{ matrix.rosdistro }}